services:
  - type: web
    name: bytenight-app
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
      - key: DATABASE_URL
        value: sqlite:////app/backend/data/bytenight.db
